name: Deploy to ECS

on:
  push:
    branches:
      - cicd-jenkins

env:
  AWS_REGION: us-east-1
  IMAGE_NAME: vprofileappimgpvt
  ECS_CLUSTER: vprofileappcluster2
  ECS_SERVICE: vprofileappsvc2
  ECS_TASK_FAMILY: vprofileapptaskdef2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIASU2YBZ76XU2C3TMK
          aws-secret-access-key: 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
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Docker image
        run: docker build -t 182183907325.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME .

      - name: Push Docker image to ECR
        run: |
          docker tag nikhil2611/vprofileappimgpvt:latest 182183907325.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME
          docker push 182183907325.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: $ECS_CLUSTER
          service: $ECS_SERVICE
          family: $ECS_TASK_FAMILY
          image: 182183907325.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME
