name: Deploy to ECS

on:
  push:
    branches:
      - cicd-jenkins

env:
  AWS_REGION: us-east-1
  IMAGE_NAME: vprofileappimgpvt
  AUTH_TOKEN: eyJwYXlsb2FkIjoiUkwwY3EwV0tvVmpUT2p1UXZtTzhkNkhQME9MYk9jN3BsS3JOY2dTaGlSVVVhamxZK3dHZmswRVUwMlY4Yk1zV0gwVU1VMUw5SCs5bVdyWmJvLzQ4V2hFVmdyY2VvWlNRV3BkMEhpcytLcG11dXp0c3l0MjdEM05OQS82Rnl0cUt1UERWWGlEZjFlTXdLSllOYXhsd0dML0xKdmljeURWN2VLWFVwUnpCWncxSWRuaXZMdUUzMm1RaGlXbG0zNVJnUVlsMjc4Y1FkZHY3Y2RHS1VYdlRKcnRsY3BLU0RUUHRuVXdVV2greHpBenhzOWxxS3lWbit5WjJrMlRmb1VpMDhQQVFxUlY1ZlZZdmNEWVRyRjgzYkVibkZLSzV6N0VTZGRYWGs4NkIramEwTnZiSXZvS0daYnFpMzNGQ1FMMGhBaDBTelkrZlNNK2xMSDBlWGhGQk9UbXlVaEZaenVmM2doZTF6NXBqZjdTQ0RFYWxJT0QvOWkzbFlXWVZoZWI2Si9uYW5NVDE1VFhRUFRWMU42YWpJYVMzQmE2WEN0R3RPREZYWVNmdi9iQWh3Q3RMSVVOczJwSStzMHVZdDZEa01aYVo2MU1NK29laXBYUGF5QkMzQmltem1oS1Zocmw5Mk1pQ0w4aDZDSU5qMkxUVXpNNzF0MVJsYkRETDd3Q3hFUDl5b3RvZHBoNWtNb21CL3ZncWlkSjN4ZjdWYksvWlVsbTdmZHFrb0hKMHlRTFVpMmZtM0Y3MWI4M2xlV3ZUcE9VRzVyeVJBQjhvUUhvcGlNRUFHQzBsMmNMei9QYnRBK0tnWWZaNlZQVll6eVplUjIvYk4vUGFXVkk5ay8zbjdUOWZZWjJkQjUzbmo3bk1OVkdTQlRZUkZ5U002enNjVzAvbjVUMTduZ0sxZ0RzUXFSR3hzMmRNRGRhejhOZWhqSldrR0lwSXZEVHFCbjcwOStObFFLd0EyWEk5OEhFemJHTWp3R0tNRHhzT0FkTmRpemg3S0tOWSsyV0F5anErdXkzSkxOTHFIbjlFQUNvUU12Tzl5eGFOUk9JUTZ0NHJhSXltSXQyV2N6MjVHUGVCcitVWlJqRjFCbGxza09iaHBWWW80Z2g5RytsOHUzQm1vcnFKR0FnbERtZHNjbU9BRmtpa3dPMG5icXVPT2wyS0dDY29kVWZxK21Vbkw1eGtkbEYxN3cyam1MUHdGQ0cxWU8waGszQWo4U25SY0FRWm8rQWFBb1FuQXNzbm9jTG0xY290M2NwUkEwenJqSGJ3QVpBWGo1OGJnSU5lY0JJWnRVSDJLZjczZFJYZE5pNFIrbUgrYTMzamR4UXNSS1pSSUF1TEVmWmNBNlZvSitCc0kva29VUXY3end3TUpSc0l3MFF4empuL1BMR3ZjdmVpcWc9PSIsImRhdGFrZXkiOiJBUUVCQUhod20wWWFJU0plUnRKbTVuMUc2dXFlZWtYdW9YWFBlNVVGY2U5UnE4LzE0d0FBQUg0d2ZBWUpLb1pJaHZjTkFRY0dvRzh3YlFJQkFEQm9CZ2txaGtpRzl3MEJCd0V3SGdZSllJWklBV1VEQkFFdU1CRUVEUHFYWm8rK3RyOERJWGNQbXdJQkVJQTdJdnZtRHBTaTNmRnpzU29icndwcE1jNVlYVEVqL05QYXI0emtIdWhGL1dzTGNUTVptc1A5K2xTaGVSQzZtUCtTeVoyNDhjY0xNNnhMS0hVPSIsInZlcnNpb24iOiIyIiwidHlwZSI6IkRBVEFfS0VZIiwiZXhwaXJhdGlvbiI6MTY3OTI3ODgzN30=

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIASU2YBZ76XU2C3TMK
          aws-secret-access-key: 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
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Docker image
        run: docker build -t 182183907325.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME .

      - name: Push Docker image to ECR
        run: |
          aws ecr --region us-east-1 | docker login -u AWS -p $AUTH_TOKEN 182183907325.dkr.ecr.us-east-1.amazonaws.com/vprofileappimgpvt
          docker tag 182183907325.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME 182183907325.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME
          docker push 182183907325.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: vprofileappcluster2
          service: vprofileappsvc2
          family: vprofileapptaskdef2
          image: 182183907325.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME
